### ISSUE TITLE
Renaming of files leads to duplicate entries in sys_file table

### ISSUE THREAD

**Issue by DenisMir** [kaystrobach/TYPO3.webdav#7]
I got the following problem when using the extension with the following workflow.

1. File exists in sys_file
2. Rename of the file via Cyberduck@WebDav
3. A new entry gets produced in sys_file with the new name (but sys_file_reference entries link to the original sys_file entry)

I'm not sure if this is by design but it makes the whole FAL referencing mechanism useless. I'm also not sure if this is a problem when using Apache+FastCGI.

**Comment by kaystrobach** [comment]
please attache the cyberduck logfile ... this way i can see what causes the problem ...

**Comment by kaystrobach** [comment]
just checked the code

see  https://github.com/kaystrobach/TYPO3.webdav/blob/master/Classes/WebDav/Nodes/Fal/File.php#L115 could you please try to replace folder with file in that line?

should be

```
	/**
	 * sets the name of the file
	 *
	 * @param string $name
	 */
	public function setName($name) {
		$this->file->setName($name);
	}
```

This was never detected before, thanks for reporting

**Comment by kaystrobach** [comment]
see ea288569a95d359843160d7ced75e3b2d5f43186 for a bugfix

**Comment by DenisMir** [comment]
Thank you for fixing the bug. This was to fast for me. :+1:

**Comment by kaystrobach** [comment]
So it works with the fix?

**Comment by DenisMir** [comment]
@kaystrobach First I thought that it would work. But it does not. I'm using now the master branch of the webdav extension with the ea28856  you introduced minutes ago. Renaming leads to the result that the file gets renamed but the db entry in `sys_file` does not get updated with the new filename in the field `identifier`. The file list module in the backend does indeed show the new name but content elements with FAL references to the image are broken now.

**Comment by kaystrobach** [comment]
damm, then i need to debug it quite a lot further, IMHO there might be other things needed ...
will try to check in the next days
