### ISSUE TITLE
Renaming of files leads to internal server error

### ISSUE THREAD

**Issue by DenisMir** [kaystrobach/TYPO3.webdav#8]
I got the following setup: Typo3 6.2 LTS (latest stable patch release), webdav@latest, Apache + FastCGI PHP

I have created a mount point for a specific user group and uploaded some files via webdav with Cyberduck to this mount point. Now I'm trying to rename these files via webdav with a user that has access rights in this group and get an internal server error. 

Here is the Cyberduck log report: 

```
MOVE /index.php/dav/FAL/WebDavTest/Bildschirmfoto_2015-05-20_um_11.15.14.png HTTP/1.1
Destination: http://.../index.php/dav/FAL/WebDavTest/test.png
Overwrite: T
Host: ...
Connection: Keep-Alive
User-Agent: Cyberduck/4.6.4 (Mac OS X/10.10.3) (x86_64)
Accept-Encoding: gzip,deflate
Authorization: Basic .....
HTTP/1.1 500 Internal Server Error
Date: Wed, 20 May 2015 10:57:09 GMT
Server: Apache
Expires: 0
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: be_typo_user=...; path=/dav/FAL/WebDavTest/; httponly
Last-Modified: Wed, 20 May 2015 10:57:09 GMT
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 20
Connection: close
Content-Type: text/html
```

I'm not sure if this is a fastcgi problem or a bug in the extension. If you need more information just drop me a message.

**Comment by kaystrobach** [comment]
Is there something in the php logs?
